# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup sparse checkout in submodule
      run: |
        cd bwv1006
        # Use git sparse-checkout command with cone mode (more efficient)
        git sparse-checkout init --cone
        git sparse-checkout set exports/
        
        # Show what files we have
        echo "Files in submodule after sparse checkout:"
        ls -la
        echo "Contents of exports directory:"
        ls -la exports/ || echo "No exports directory found"
        
    - name: Create deployment directory
      run: |
        mkdir deploy
    
        # Copy root files
        cp index.html deploy/
        
        # Copy media directory  
        cp -r media deploy/
        
        # Copy bwv1006 submodule with exports directory preserved
        cp -r bwv1006 deploy/
        
        # Show deployment contents and size
        echo "Deployment contents:"
        find deploy/ -type f -exec ls -lah {} \;
        echo ""
        echo "Directory structure:"
        tree deploy/ || find deploy/ -type d
        echo ""
        echo "Total deployment size:"
        du -sh deploy/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './deploy'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4